name: gnn
channels:
  - conda-forge
dependencies:
  - astropy
  - fa2_modified
  - gputil
  - h5py
  - imageio
  - ipython
  - matplotlib
  - networkx
  - numpy
  - pandas
  - pip
  - prettytable
  - pydantic
  - pysr
  - pytorch
  - PyYAML
  - scikit-image
  - scipy
  - seaborn
  - tifffile
  - torchvision
  - tqdm
  - umap-learn
  - vispy
  - pip:
    - geomloss
    - torch_geometric
