[project]
name = "ParticleGraph"
version = "0.1.0"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages]
find = {}  # Scan the project directory with the default parameters

[tool.jupytext]
formats = "ipynb,py:percent"

