description: 'Wave propagation'
dataset: 'wave_slit_ter'

simulation:
  params: [[0.2],[1.4],[2.6],[3.8],[5.0]]
  min_radius: 0
  max_radius: 0.3
  diffusion_coefficients: [[0],[0.6],[0.8],[1],[0.4]]
  n_particles: 10000
  n_particle_types: 5
  n_interactions: 5
  n_nodes: 10000
  n_node_types:  5
  n_frames: 8000
  delta_t: 0.125
  dpos_init: 0
  boundary: 'periodic'
  node_value_map: 'pattern_24.tif'
  node_coeff_map: 'pics_slits.tif'
  beta: 1.E-2
  start_frame: 0

graph_model:
  particle_model_name: ''
  mesh_model_name: 'WaveMesh'
  prediction: '2nd_derivative'
  input_size: 3
  output_size: 1
  hidden_dim: 16
  n_mp_layers: 5
  aggr_type: 'add'
  mesh_aggr_type: 'add'
  embedding_dim: 2
  update_type: 'none'

plotting:
  colormap: 'viridis'
  arrow_length: 10

training:
  n_epochs: 20
  batch_size: 8
  small_init_batch_size: True
  n_runs: 2
  sparsity: 'none'
  data_augmentation: True
  cluster_method: 'distance_embedding'
  cluster_distance_threshold: 0.1
  fix_cluster_embedding: True

  device: 'auto'
